hunter_add_package(Eigen)
find_package(Eigen3 REQUIRED)
if(NOT EIGEN3_INCLUDE_DIR MATCHES "${HUNTER_ROOT}/.*")
  message(FATAL_ERROR "Did not use hunter to download eigen")
endif()

hunter_add_package(CFitsIO)
find_package(CFitsIO)
if(NOT CFitsIO_INCLUDE_DIR MATCHES "${HUNTER_ROOT}/.*")
  message(FATAL_ERROR "Did not use hunter to download CFitsIO")
endif()
